---
baseurl: https://example.com
languageCode: en-us
title: Hugo Tania
theme: hugo-tania
paginate: 6
disqusShortname: https-hugo-tania-netlify-app
params:
  titleEmoji: 
  titleLogo: favicon.ico
  enableFootnotes: true
  siteName: Hugo Tania is Amazing
  siteDesc: Hugo is Absurdly Fast!
  author: Hugo Tania
  colorScheme:
    toggle: true
    default: auto
  maxCategoryToShow: 10
  socialOptions:
    dev-to: 
    email: 
    facebook: 
    github: 
    instagram: 
    linkedin: 
    medium: 
    stack-overflow: 
    steam: 
    telegram: 
    twitter: 
    twitch: 
    whatsapp: 
  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP
menu:
  footer:
  - url: "/index.xml"
    name: RSS
    weight: 1
  header:
  - url: https://jongrpl1.eu.org
    name: Home
    weight: 1
  - url: "/articles/"
    name: Articles
    weight: 2
markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
